<?php

    use \Drupal\node\Entity\NodeType;
    use \Drupal\Core\Entity\EntityInterface;

/**
 * @param $variable
 * @param $entity
 * @return mixed
 */
 function events_preprocess_page(&$variable, $entity ) {

     $entity = \Drupal::routeMatch()->getParameter('events_entity');
     //kint($entity);
     //exit;
     if ($entity) {
         $entitytype = $entity->bundle();
         //kint($entitytype);
         //exit;

         $form = \Drupal::formBuilder()
             ->getForm('Drupal\events\Form\EventsForm');
         //kint($form);
         //exit;
         if('events_entity' == $entitytype) {
             $variable['my_events'] = $form;
     //kint($variable);
             return $variable;
         }
         return $variable;
     }
     return $variable;

 }

