<?php

    use \Drupal\node\Entity\NodeType;
    use \Drupal\Core\Entity\EntityInterface;

/**
 * @param $variable
 * @param $entity
 * @return mixed
 */
 function events_preprocess_page(&$variable, $entity ) {
     $entity = \Drupal::routeMatch()
         ->getParameter('events_entity');

     if ($entity) {
         $entitytype = $entity->bundle();

         $form = \Drupal::formBuilder()
             ->getForm('Drupal\events\Form\EventsForm');
         @$checkurlid = $_GET['check'];

         if('events_entity' == $entitytype) {
             if($checkurlid != 1) {
                 $variable['form_events'] = $form;
             }
                 $variable['checkmail'] = $checkurlid;
         }
         return $variable;
     }
     return $variable;
 }

