<?php

    use \Drupal\node\Entity\NodeType;
    use \Drupal\Core\Entity\EntityInterface;
 /**
  * Implements hook_preprocess_HOOK() for radix-brenham--node--2.html.twig.
  */
 function events_preprocess_node(&$variable, $node) {

     $node = \Drupal::routeMatch()->getParameter('node');
     if ($node) {
         $nodetype = $node->bundle();
         //ksm($node);
         $form = \Drupal::formBuilder()
             ->getForm('Drupal\events\Form\EventsForm');

         if('events' == $nodetype) {
             $variable['my_events'] = $form;
             return $variable;
         }
         return $variable;
     }
     return $variable;

 }

 function events_theme(){

     return [
         'test' => [
             'items' => NULL,
         ],
     ];

 }
